# Generated by Django 5.0.4 on 2024-04-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customerprofiles_author_supplierprofiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierprofiles',
            old_name='phone_number',
            new_name='supplier_phone',
        ),
    ]
